# Implémentation IPF

In [59]:
import numpy as np

## Données de couplages

In [132]:
data=np.array(
    [
        [126,24],
        [24,26],
    ]
)
ex_cols=np.array([175,30])
ex_lines=np.array([150,55])
data.sum(axis=0)

array([150,  50])

In [140]:
def col_adjust(data,ex_cols):
    cols=data.sum(axis=0)
    ratio=ex_cols/cols
    return data*ratio

def line_adjust(data,ex_lines):
    lines=data.sum(axis=1)
    ratio=ex_lines/lines
    return data*ratio.reshape(lines.shape[0],1)


def step(data, ex_cols,ex_lines):
    data=col_adjust(data,ex_cols)
    data=line_adjust(data, ex_lines)
    return data

def convergence(data, ex_cols,ex_lines,err=1e-2):
    prev_cost=data.sum()
    data=step(data,ex_cols,ex_lines)
    cost=data.sum()
    i=1
    while(cost-prev_cost>err):
        data=step(data,ex_cols,ex_lines)
        prev_cost=cost
        cost=data.sum()
        i+=1
    print(f"Convergence après {i} itérations")
    return data

d=data.copy()
print(d)

[[126  24]
 [ 24  26]]


In [141]:
convergence(d,ex_cols,ex_lines)



Convergence après 2 itérations


array([[137.95232383,  12.04767617],
       [ 36.74746866,  18.25253134]])