# Modifications de résultats des sondages

## Import préliminaires des librairies

In [1]:
import re
import numpy as np
import pandas as pd
import locale 
from locale import atof
# Régression linéaire
from sklearn.linear_model import LinearRegression

# Read files
import PyPDF2
from pdfminer.high_level import extract_text

# Perso
from importlib.machinery import SourceFileLoader
tools = SourceFileLoader('methods', '../methods.py').load_module()
from methods import *

In [2]:
fp="rapport/2021-03-03.pdf"
text = extract_text(fp,page_numbers=[10])
question1="Êtes-vous  satisfait  ou  mécontent  d"
question2="Êtes-vous satisfait ou mécontent d"
# print(text.find(question1))
# print(text.find(question2))
# print(len(question2))
print(re.sub('\.\.\. (?![\n])','...\n',text))

La cote de confiance du Président de la République
Détail des résultats
par catégories sociodémographiques et professionnelles

Total

100

Tout à fait 
confiance
6

Plutôt confiance

Sans opinion

Pas vraiment 
confiance
29

Pas confiance du 
tout
31

TOTAL 
CONFIANCE
34

TOTAL
PAS CONFIANCE
60

En %

Ensemble
SEXE DU REPONDANT
Homme
Femme
AGE DU REPONDANT
18-24 ans
25-34 ans
35-49 ans
50-64 ans
65 ans et plus
PROFESSION DU REPONDANT
Actifs
Artisan, commerçant (*)
CSP+
Cadre, profession intellectuelle supérieure
Profession intermédiaire
CSP-
Employé
Ouvrier
Inactifs
Retraité
Autre Inactif

CATEGORIE D'AGGLOMERATION
Communes rurales
Communes urbaines de province
De 2.000 à moins de 20.000 hab.
De 20.000 à moins de 100.000 hab.
100.000 hab. et plus
Agglomération parisienne

100
100

100
100
100
100
100

100
100
100
100
100
100
100
100
100
100
100

100
100
100
100
100
100

8
4

11
5
5
6
4

5
8
5
7
3
4
4
6
7
5
10

7
6
5
8
5
4

28

31
26

26
28
25
30
32

29
34
35
41
32
22
25
19
28
31
23

2

In [3]:
with open(fp,"rb") as pdf_file:
    pdf_reader= PyPDF2.PdfFileReader(pdf_file)
    isEncrypted = pdf_reader.getIsEncrypted()
    nbPages= pdf_reader.numPages

    # Define columns
    page_content=pdf_reader.getPage(11).extractText()
page_content

"12\nL'Observatoire politique \n\nMars 2021\n04/03/2021\nDétail des résultats\nselon la préférence partisane et le vote à la présidentielle\n* Résultats à interpréter avec prudence compte\n-\ntenu des effectifs de répondants\nEn %\nTotal\nTout à fait \nconfiance\nPlutôt confiance\nPas vraiment \nconfiance\nPas confiance du \ntout\nSans opinion\nTOTAL\nCONFIANCE\nTOTAL\nPAS CONFIANCE\nEnsemble\n100\n6\n28\n29\n31\n6\n34\n60\nPREFERENCE PARTISANE\nTOTAL GAUCHE\n100\n5\n23\n34\n35\n3\n28\n69\nLa France Insoumise\n100\n3\n13\n30\n52\n2\n16\n82\nEurope Ecologie \n-\nLes Verts\n100\n6\n17\n45\n26\n6\n23\n71\nParti Socialiste / \nGénération.s\n/ PRG\n100\n4\n41\n34\n20\n1\n45\n54\nTOTAL EN MARCHE / MODEM\n100\n22\n71\n3\n4\n93\n7\nLa République en Marche !\n100\n26\n71\n0\n3\n97\n3\nTOTAL DROITE\n100\n3\n42\n27\n26\n2\n45\n53\nLes Républicains\n100\n2\n48\n27\n21\n2\n50\n48\nLe Rassemblement National\n100\n1\n7\n31\n59\n2\n8\n90\nSans préférence partisane\n100\n3\n23\n33\n29\n12\n26\n62\nVOTE

# Extraction des données avec PyPDF2
PyPDF2 semble être constant dans la forme d'extraction des données de Elab.
La structure des données ainsi que les détails d'extraction sont précisés ci-dessous:
* Elabe fourni les données détaillées pour deux personnalités que sont le président de la République et le premier ministre. Les noms n'étant pas indiqués sur la page de données, il faut les extraire ailleurs ou les préciser à la main.
* Il y a deux pages successives de données par individus
* Les catégories principales sont indiquées en capitales
* Il existe des catégories secondaires et tertiaires sans différenciation possible. Elles seront traités comme sous catégories.
* La base de chaque catégories n'est pas précisée, il faudra donc utiliser de la régression linéaire pour tenter de les retrouver
* Les trous dans les données ne sont pas visible. Il faut un système de vérification.
* Les variations ne sont pas données

__Format des données__
* Les données sont fournis en lisant les lignes dans l'ordre
* Chaque cellule est extraite par PyPDF2 une à la fois en introduisant un saut de ligne
* Les blancs dans les données ne créént pas de fusion d'information mais disparaissent sans faire de double saut de lignes
* Le caractère '__-__' compromet les cellules et induit un ou plusieurs sauts malencontreux :
    * Si le '-' apparait au milieu d'un texte, il induit un _double saut de ligne_ (ex: 18-24 ans)
    * Si le '-' apparait à la fin d'un texte il induit un _seul_ saut de ligne supplémentaire avant sont apparition (CSP-)  
* Il faudra donc préformater le texte au préalable


## Extract content (to delete later)

In [4]:
def get_page_content(num_page,fp)->str:
    with open(fp,"rb") as pdf_file:
        pdf_reader= PyPDF2.PdfFileReader(pdf_file)
        isEncrypted = pdf_reader.getIsEncrypted()
        nbPages= pdf_reader.numPages
        return pdf_reader.getPage(num_page-1).extractText()

    # Define columns
page_content=get_page_content(2,fp)
page_content

"Interrogation\nFiche technique\n2\n\nMode de recueil et dates de terrain\nLa\nreprésentativité\nde\n\na\nété\nassurée\nselon\nla\nméthode\ndes\nquotas\nappliquée\naux\nvariables\nsuivantes\n:\nsexe,\nâge\net\nprofession\nde\n\naprès\nstratification\npar\nrégion\net\ncatégorie\n\n.\nEchantillon de \n1 003  \npersonnes représentatif de la population française âgée de 18 ans et plus.\nInterrogation par Internet les \n2 et 3 mars 2021\n.\n04/03/2021\nL'Observatoire politique \n\nMars 2021\n"

## Préformatage

In [5]:
##Préformatage
def preformatage(page_content)->str:
    #Remplacement des données d'age
    page_content=page_content.replace('18\n-\n24 ans','18-24 ans')
    page_content=page_content.replace('25\n-\n34 ans','25-34 ans')
    page_content=page_content.replace('35\n-\n49 ans','35-49 ans')
    page_content=page_content.replace('50\n-\n64 ans','50-64 ans')
    # Remplacement CSP-
    page_content=page_content.replace('CSP\n-','CSP-')
    # Remplacement EELV
    page_content=page_content.replace('Europe Ecologie \n-\nLes Verts','Europe Ecologie Les Verts')
    # Noms de candidats
    page_content=page_content.replace('Jean\n-\n','Jean-')
    # Remplacement /
    page_content=page_content.replace('/ \n','/ ')
    page_content=page_content.replace('\n/','/')
    # Remplacement Total .. en minuscule
    page_content=page_content.replace('TOTAL GAUCHE','Total Gauche')
    page_content=page_content.replace('TOTAL EN MARCHE / MODEM','Total en Marche / MODEM')
    page_content=page_content.replace('TOTAL DROITE','Total Droite')
    # Suppression fin de texte
    page_content=page_content.replace('\nLa cote de confiance du Président de la République','')
    page_content=page_content.replace('\nLa cote de confiance du Premier ministre','')
    # Suppression des notes de bas de pages
    page_content=page_content.replace(' (*)','')
    page_content=page_content.replace('(*)','')
    # Suppression du dernier saut de ligne
    page_content=page_content.rstrip('\n')
    return page_content

preformatage(page_content)


"Interrogation\nFiche technique\n2\n\nMode de recueil et dates de terrain\nLa\nreprésentativité\nde\n\na\nété\nassurée\nselon\nla\nméthode\ndes\nquotas\nappliquée\naux\nvariables\nsuivantes\n:\nsexe,\nâge\net\nprofession\nde\n\naprès\nstratification\npar\nrégion\net\ncatégorie\n\n.\nEchantillon de \n1 003  \npersonnes représentatif de la population française âgée de 18 ans et plus.\nInterrogation par Internet les \n2 et 3 mars 2021\n.\n04/03/2021\nL'Observatoire politique \n\nMars 2021"

## Extraction de la base

In [6]:
def extract_base(fp,num_page=2)->int:
    page_content=get_page_content(num_page,fp)
    text_deb='Echantillon de \n'
    text_fin='\npersonnes'
    i_deb=page_content.find(text_deb)+len(text_deb)
    i_fin=page_content.find(text_fin)
    base=int(page_content[i_deb:i_fin].rstrip().replace(' ',''))
    return base
extract_base(fp)

1003

## Création du modèle de Dataframe

In [7]:
df=pd.DataFrame(columns=['Nom','Base','Date','Categorie','Groupe','tres_positif','positif','negatif','tres_negatif','nsp','total_positif','total_negatif'])

## Extraction de page formattée

In [8]:
def extract_series(data,i,columns,nom,base,date,prv_categorie)->pd.Series:
    """Extrait une serie de data à partir de l'indice i jusqu'à la prochaine valeur non digit

    Args:
        data (list): Toutes les données dans une liste 
        i (int): Indice courant dans les données
        columns (list): Liste des noms de colonnes 
        nom (str): Nom de la personnalité
        base (int): Nombre de sondés
        date (datetime.date): Date du sondage

    Returns:
        pd.Series: La serie contenant les valeurs à stocker
        int: new index
    """
    values=[nom,base,date]
    #Catégorie
    if data[i].isupper() and '+' not in data[i] and '-' not in data[i]:
        values.append(data[i])
        i+=1
    else:
        values.append(prv_categorie)
    #Groupe
    values.append(data[i])
    # On saut la cellule qui contient le 100% et qui ne sert a rien
    i+=2
    while i<len(data) and re.match('^\d+$',data[i]):
        values.append(float(data[i]))
        i+=1
    # Vérification
    while len(values)!=len(columns):
        print(values)
        j=int(input('Où faut-il ajouter un zéro ? (1-7)'))+4
        values=values[:j]+[0.0]+values[j:]
    return pd.Series(values,index=columns),i



def extract_detailled_page(page_content,df,nom,base,date)->pd.DataFrame:
    """
    Extrait une page du pdf et l'ajout au dataframe.
    
    Parameters
    ----------
    page_content: texte formatté de la page dot l'on souhaite extraire les données
    df: Dataframe pour stocker les données
    nom: Nom de la personnalité 
    base: Base d'étude (à compléter par regression plus tard)
    date: Date du sondage

    Returns
    -------
    Dataframe
        Dataframe df avec les nouvelles données
    """
    indice_debut=page_content.find('Ensemble')
    data=page_content[indice_debut:].split('\n')
    i=0
    cat='Ensemble'
    while i < len(data):
        if not re.match('^\d+$',data[i]):
            s,i=extract_series(data,i,df.columns,nom,base,date,cat)
            cat=s.Categorie
            df=df.append(s,ignore_index=True)
    return df
            

## Extraction pour une personnalité

In [9]:
def extract_detailled_perso(df,fp,page_indexes,nom,base,date)->pd.DataFrame:
    """Extrait les données sur toutes les pages pour une personnalité

    Args:
        df (pandas.Dataframe): Dataframe stockant les données
        fp (str): filepath du fichier à lire
        page_indexes (list): Liste des pages à extraire
        nom (str): Nom de la personnalité
        base (int): Nb de sondés
        date (datetime.date): Date du sondate
        inline (bool): Si True modification en ligne

    Returns:
        pd.DataFrame: Dataframe étendu des nouvelles données
    """
    for i in page_indexes:
        page_content=preformatage(get_page_content(i,fp))
        df=extract_detailled_page(page_content,df,nom,base,date)
    df=df.drop_duplicates(ignore_index=True)
    return df

        

In [10]:
df=pd.DataFrame(columns=['Nom','Base','Date','Categorie','Groupe','tres_positif','positif','negatif','tres_negatif','nsp','total_positif','total_negatif'])
date='2021-03-03'
filepath='rapport/{}.pdf'.format(date)
president='Emmanuel MACRON'
page_president=[11,12]
ministe='Edouard PHILIPPE'
page_ministre=[13,14]
base=extract_base(filepath)
df=extract_detailled_perso(df,filepath,page_president,president,base,date)
df=extract_detailled_perso(df,filepath,page_ministre,ministe,base,date)
df

['Emmanuel MACRON', 1003, '2021-03-03', 'PROFESSION DU REPONDANT', 'Artisan, commerçant', 8.0, 34.0, 29.0, 29.0, 42.0, 58.0]
['Emmanuel MACRON', 1003, '2021-03-03', 'PREFERENCE PARTISANE', 'Total en Marche / MODEM', 22.0, 71.0, 3.0, 4.0, 93.0, 7.0]
['Emmanuel MACRON', 1003, '2021-03-03', 'PREFERENCE PARTISANE', 'La République en Marche !', 26.0, 71.0, 0.0, 3.0, 97.0, 3.0]
['Emmanuel MACRON', 1003, '2021-03-03', 'VOTE PRESIDENTIELLE 2017 (1ER TOUR)', 'Benoît HAMON', 3.0, 32.0, 31.0, 34.0, 35.0, 65.0]
['Edouard PHILIPPE', 1003, '2021-03-03', 'PROFESSION DU REPONDANT', 'Artisan, commerçant', 26.0, 37.0, 35.0, 3.0, 26.0, 72.0]
['Edouard PHILIPPE', 1003, '2021-03-03', 'VOTE PRESIDENTIELLE 2017 (1ER TOUR)', 'Benoît HAMON', 30.0, 26.0, 44.0, 0.0, 30.0, 70.0]


Nom  Base        Date                            Categorie  \
0    Emmanuel MACRON  1003  2021-03-03                             Ensemble   
1    Emmanuel MACRON  1003  2021-03-03                    SEXE DU REPONDANT   
2    Emmanuel MACRON  1003  2021-03-03                    SEXE DU REPONDANT   
3    Emmanuel MACRON  1003  2021-03-03                     AGE DU REPONDANT   
4    Emmanuel MACRON  1003  2021-03-03                     AGE DU REPONDANT   
..               ...   ...         ...                                  ...   
83  Edouard PHILIPPE  1003  2021-03-03  VOTE PRESIDENTIELLE 2017 (1ER TOUR)   
84  Edouard PHILIPPE  1003  2021-03-03  VOTE PRESIDENTIELLE 2017 (1ER TOUR)   
85  Edouard PHILIPPE  1003  2021-03-03  VOTE PRESIDENTIELLE 2017 (2ND TOUR)   
86  Edouard PHILIPPE  1003  2021-03-03  VOTE PRESIDENTIELLE 2017 (2ND TOUR)   
87  Edouard PHILIPPE  1003  2021-03-03  VOTE PRESIDENTIELLE 2017 (2ND TOUR)   

                           Groupe  tres_positif  positif  negatif  \
0                        Ensemble           6.0     28.0     29.0   
1                           Homme           8.0     31.0     26.0   
2                           Femme           4.0     26.0     32.0   
3                       18-24 ans          11.0     26.0     35.0   
4                       25-34 ans           5.0     28.0     37.0   
..                            ...           ...      ...      ...   
83                  Marine LE PEN           2.0     14.0     31.0   
84  Abstention, vote blanc ou nul           3.0     16.0     34.0   
85                Emmanuel MACRON           6.0     43.0     28.0   
86                  Marine LE PEN           1.0     15.0     31.0   
87  Abstention, vote blanc ou nul           2.0     12.0     35.0   

    tres_negatif   nsp  total_positif  total_negatif  
0           31.0   6.0           34.0           60.0  
1           32.0   3.0           39.0           58.0  
2           30.0   8.0           30.0           62.0  
3           19.0   9.0           37.0           54.0  
4           23.0   7.0           33.0           60.0  
..           ...   ...            ...            ...  
83          49.0   4.0           16.0           80.0  
84          32.0  15.0           19.0           66.0  
85          19.0   4.0           49.0           47.0  
86          48.0   5.0           16.0           79.0  
87          39.0  12.0           14.0           74.0  

[88 rows x 12 columns]

# Correction des bases

In [11]:
for c  in df.Categorie.unique():
    print('{} :[{}]'.format(c,','.join(["'"+x+"'" for x in df[df.Categorie==c].Groupe.unique()])))

Ensemble :['Ensemble']
SEXE DU REPONDANT :['Homme','Femme']
AGE DU REPONDANT :['18-24 ans','25-34 ans','35-49 ans','50-64 ans','65 ans et plus']
PROFESSION DU REPONDANT :['Actifs','Artisan, commerçant','CSP+','Cadre, profession intellectuelle supérieure','Profession intermédiaire','CSP-','Employé','Ouvrier','Inactifs','Retraité','Autre Inactif']
CATEGORIE D'AGGLOMERATION :['Communes rurales','Communes urbaines de province','De 2.000 à moins de 20.000 hab.','De 20.000 à moins de 100.000 hab.','100.000 hab. et plus','Agglomération parisienne']
PREFERENCE PARTISANE :['Total Gauche','La France Insoumise','Europe Ecologie Les Verts','Parti Socialiste / Génération.s/ PRG','Total en Marche / MODEM','La République en Marche !','Total Droite','Les Républicains','Le Rassemblement National','Sans préférence partisane']
VOTE PRESIDENTIELLE 2017 (1ER TOUR) :['Jean-Luc MELENCHON','Benoît HAMON','Emmanuel MACRON','François FILLON','Marine LE PEN','Abstention, vote blanc ou nul']
VOTE PRESIDENTIELLE 2

In [12]:
# CategorieX, GroupeX, CategorieY, GroupeY
relations=[
    ('SEXE DU REPONDANT' ,['Homme','Femme'],'Ensemble','Ensemble'),
    ('AGE DU REPONDANT' ,['18-24 ans','25-34 ans','35-49 ans','50-64 ans','65 ans et plus'],'Ensemble','Ensemble'),
    ('PROFESSION DU REPONDANT' ,['Actifs','Inactifs'],'Ensemble','Ensemble'),
    ('PROFESSION DU REPONDANT' ,['Artisan, commerçant','CSP+','CSP-'],'PROFESSION DU REPONDANT','Actifs'),
    ('PROFESSION DU REPONDANT' ,['Cadre, profession intellectuelle supérieure','Profession intermédiaire'],'PROFESSION DU REPONDANT','CSP+'),
    ('PROFESSION DU REPONDANT' ,['Employé','Ouvrier'],'PROFESSION DU REPONDANT','CSP-'),
    ('PROFESSION DU REPONDANT' ,['Retraité','Autre Inactif'],'PROFESSION DU REPONDANT','Inactifs'),
    ("CATEGORIE D'AGGLOMERATION" ,['Communes rurales','Communes urbaines de province','Agglomération parisienne'],'Ensemble','Ensemble'),
    ("CATEGORIE D'AGGLOMERATION" ,['De 2.000 à moins de 20.000 hab.','De 20.000 à moins de 100.000 hab.','100.000 hab. et plus'],"CATEGORIE D'AGGLOMERATION",'Communes urbaines de province'),
    ('PREFERENCE PARTISANE' ,['Total Gauche','Total en Marche / MODEM','Total Droite','Le Rassemblement National','Sans préférence partisane'],'Ensemble','Ensemble'),
    ('PREFERENCE PARTISANE' ,['La France Insoumise','Europe Ecologie Les Verts','Parti Socialiste / Génération.s/ PRG'],'PREFERENCE PARTISANE','Total Gauche'),
    ('PREFERENCE PARTISANE' ,['La République en Marche !'],'PREFERENCE PARTISANE','Total en Marche / MODEM'),
    ('PREFERENCE PARTISANE' ,['Les Républicains'],'PREFERENCE PARTISANE','Total Droite'),
    ('VOTE PRESIDENTIELLE 2017 (1ER TOUR)' ,['Jean-Luc MELENCHON','Benoît HAMON','Emmanuel MACRON','François FILLON','Marine LE PEN','Abstention, vote blanc ou nul'],'Ensemble','Ensemble'),
    ('VOTE PRESIDENTIELLE 2017 (2ND TOUR)' ,['Emmanuel MACRON','Marine LE PEN','Abstention, vote blanc ou nul'],'Ensemble','Ensemble'),   
]

In [13]:
df_alter=recompute_base(df,relations,df.columns[5:])

['Homme', 'Femme']
[473. 524.]
['18-24 ans', '25-34 ans', '35-49 ans', '50-64 ans', '65 ans et plus']
[174.  63. 323. 223. 221.]
['Actifs', 'Inactifs']
[532. 469.]
['Artisan, commerçant', 'CSP+', 'CSP-']
[ 73. 205. 246.]
['Cadre, profession intellectuelle supérieure', 'Profession intermédiaire']
[ 78. 124.]
['Employé', 'Ouvrier']
[125. 121.]
['Retraité', 'Autre Inactif']
[320. 150.]
['Communes rurales', 'Communes urbaines de province', 'Agglomération parisienne']
[295. 540. 154.]
['De 2.000 à moins de 20.000 hab.', 'De 20.000 à moins de 100.000 hab.', '100.000 hab. et plus']
[150. 104. 284.]
['Total Gauche', 'Total en Marche / MODEM', 'Total Droite', 'Le Rassemblement National', 'Sans préférence partisane']
[344. 112.  86. 100. 343.]
['La France Insoumise', 'Europe Ecologie Les Verts', 'Parti Socialiste / Génération.s/ PRG']
[152.  71. 113.]
['La République en Marche !']
[104.]
['Les Républicains']
[80.]
['Jean-Luc MELENCHON', 'Benoît HAMON', 'Emmanuel MACRON', 'François FILLON', 'Mari

In [14]:
df_alter.head(30)

Nom  Base        Date                  Categorie  \
0   Emmanuel MACRON  1003  2021-03-03                   Ensemble   
1   Emmanuel MACRON   473  2021-03-03          SEXE DU REPONDANT   
2   Emmanuel MACRON   524  2021-03-03          SEXE DU REPONDANT   
3   Emmanuel MACRON   174  2021-03-03           AGE DU REPONDANT   
4   Emmanuel MACRON    63  2021-03-03           AGE DU REPONDANT   
5   Emmanuel MACRON   323  2021-03-03           AGE DU REPONDANT   
6   Emmanuel MACRON   223  2021-03-03           AGE DU REPONDANT   
7   Emmanuel MACRON   221  2021-03-03           AGE DU REPONDANT   
8   Emmanuel MACRON   532  2021-03-03    PROFESSION DU REPONDANT   
9   Emmanuel MACRON    73  2021-03-03    PROFESSION DU REPONDANT   
10  Emmanuel MACRON   205  2021-03-03    PROFESSION DU REPONDANT   
11  Emmanuel MACRON    78  2021-03-03    PROFESSION DU REPONDANT   
12  Emmanuel MACRON   124  2021-03-03    PROFESSION DU REPONDANT   
13  Emmanuel MACRON   246  2021-03-03    PROFESSION DU REPONDANT   
14  Emmanuel MACRON   125  2021-03-03    PROFESSION DU REPONDANT   
15  Emmanuel MACRON   121  2021-03-03    PROFESSION DU REPONDANT   
16  Emmanuel MACRON   469  2021-03-03    PROFESSION DU REPONDANT   
17  Emmanuel MACRON   320  2021-03-03    PROFESSION DU REPONDANT   
18  Emmanuel MACRON   150  2021-03-03    PROFESSION DU REPONDANT   
19  Emmanuel MACRON   295  2021-03-03  CATEGORIE D'AGGLOMERATION   
20  Emmanuel MACRON   540  2021-03-03  CATEGORIE D'AGGLOMERATION   
21  Emmanuel MACRON   150  2021-03-03  CATEGORIE D'AGGLOMERATION   
22  Emmanuel MACRON   104  2021-03-03  CATEGORIE D'AGGLOMERATION   
23  Emmanuel MACRON   284  2021-03-03  CATEGORIE D'AGGLOMERATION   
24  Emmanuel MACRON   154  2021-03-03  CATEGORIE D'AGGLOMERATION   
25  Emmanuel MACRON   344  2021-03-03       PREFERENCE PARTISANE   
26  Emmanuel MACRON   152  2021-03-03       PREFERENCE PARTISANE   
27  Emmanuel MACRON    71  2021-03-03       PREFERENCE PARTISANE   
28  Emmanuel MACRON   113  2021-03-03       PREFERENCE PARTISANE   
29  Emmanuel MACRON   112  2021-03-03       PREFERENCE PARTISANE   

                                         Groupe  tres_positif  positif  \
0                                      Ensemble           6.0     28.0   
1                                         Homme           8.0     31.0   
2                                         Femme           4.0     26.0   
3                                     18-24 ans          11.0     26.0   
4                                     25-34 ans           5.0     28.0   
5                                     35-49 ans           5.0     25.0   
6                                     50-64 ans           6.0     30.0   
7                                65 ans et plus           4.0     32.0   
8                                        Actifs           5.0     29.0   
9                           Artisan, commerçant           8.0     34.0   
10                                         CSP+           5.0     35.0   
11  Cadre, profession intellectuelle supérieure           7.0     41.0   
12                     Profession intermédiaire           3.0     32.0   
13                                         CSP-           4.0     22.0   
14                                      Employé           4.0     25.0   
15                                      Ouvrier           6.0     19.0   
16                                     Inactifs           7.0     28.0   
17                                     Retraité           5.0     31.0   
18                                Autre Inactif          10.0     23.0   
19                             Communes rurales           7.0     24.0   
20                Communes urbaines de province           6.0     29.0   
21              De 2.000 à moins de 20.000 hab.           5.0     26.0   
22            De 20.000 à moins de 100.000 hab.           8.0     28.0   
23                         100.000 hab. et plus           5.0     31.0   
24                     Agglomération parisienne          

In [15]:

# with open("rapport/2020-10-14.pdf","rb") as pdf_file:
#     pdf_report= PyPDF2.PdfFileReader(pdf_file)
#     isEncrypted = pdf_report.getIsEncrypted()
#     nbPages= pdf_report.numPages

#     page1=pdf_report.getPage(15)
#     text=page1.extractText().replace(',','.')
#     text = extract_text(pdf_file,page_numbers=[14])

# print(text)

print(df.isnull().values.any())
df.head(10)
df.describe()
df[df.Base==0]

False


Empty DataFrame
Columns: [Nom, Base, Date, Categorie, Groupe, tres_positif, positif, negatif, tres_negatif, nsp, total_positif, total_negatif]
Index: []

## Find mistakes and try to correct them

In [16]:
def find_fav_mistake(df):
    tfav=df['Très favorable']
    pfav=df['Plutôt favorable']
    stfav=df['ST Favorable']
    fav_df= df[np.abs(tfav+pfav-stfav)>0.11]
    return fav_df

def find_def_mistake(df):
    tdef=df['Très défavorable']
    pdef=df['Plutôt défavorable']
    stdef=df['ST Défavorable']
    def_df= df[np.abs(tdef+pdef-stdef)>0.11]
    return def_df

def find_nsp_mistake(df):
    stfav=df['ST Favorable']
    stdef=df['ST Défavorable']
    nsp=df['Nsp']
    tot_df= df[np.abs(stfav+stdef+nsp-100)>0.11]
    return tot_df

def find_mistake(df):
    fav_df= find_fav_mistake(df)
    def_df= find_def_mistake(df)
    tot_df=find_nsp_mistake(df)
    error_df=pd.concat([fav_df,def_df,tot_df])
    return error_df

In [17]:
def realign_fav(df,i=0,imax=-1):
    df_err=find_fav_mistake(df)
    zeros_cols= [x for x in ["Très favorable","Plutôt favorable","ST Favorable"] if df[x].all()==0]
    if imax==-1:
        imax=len(zeros_cols)*len(df)
    if not df_err.empty and i<=imax:
        col=zeros_cols[0]
        values=df_err[col].tolist()
        values=values[1:]+[values[0]]
        df.loc[df_err.index,col]=values
        df=realign_fav(df,i+1)
    return df

def realign_def(df,i=0,imax=-1):
    df_err=find_fav_mistake(df)
    zeros_cols= [x for x in ["Très défavorable","Plutôt défavorable","ST Défavorable"] if df[x].all()==0]
    if imax==-1:
        imax=len(zeros_cols)*len(df)
    if not df_err.empty and i<=imax:
        col=zeros_cols[0]
        values=df_err[col].tolist()
        values=values[1:]+[values[0]]
        df.loc[df_err.index,col]=values
        df=realign_def(df,i+1)
    return df

def realign_nsp(df,i=0,imax=-1):
    df_err=find_fav_mistake(df)
    zeros_cols= [x for x in ["ST Favorable","ST Défavorable","Nsp"] if df[x].all()==0]
    if imax==-1:
        imax=len(zeros_cols)*len(df)
    if not df_err.empty and i<=imax:
        col=zeros_cols[0]
        values=df_err[col].tolist()
        values=values[1:]+[values[0]]
        df.loc[df_err.index,col]=values
        df=realign_nsp(df,i+1)
    return df

    



In [18]:
def correct_mistakes(df):
    df_err=find_fav_mistake(df)
    for nom in df_err.Nom.unique():
        for cat in df_err[df_err.Nom==nom].Categorie.unique():
            cond=((df_err.Nom==nom) & (df_err.Categorie==cat))
            df_err.loc[cond]=realign_fav(df_err[cond])
    df.loc[df_err.index]=df_err

    df_err=find_def_mistake(df)
    for nom in df_err.Nom.unique():
        for cat in df_err[df_err.Nom==nom].Categorie.unique():
            cond=((df_err.Nom==nom) & (df_err.Categorie==cat))
            df_err.loc[cond]=realign_def(df_err[cond])
    df.loc[df_err.index]=df_err

    df_err=find_nsp_mistake(df)
    for nom in df_err.Nom.unique():
        for cat in df_err[df_err.Nom==nom].Categorie.unique():
            cond=((df_err.Nom==nom) & (df_err.Categorie==cat))
            df_err.loc[cond]=realign_nsp(df_err[cond])
    df.loc[df_err.index]=df_err
    return df

In [19]:
df_err=find_mistake(df)
if len(df_err)>0:
    index=df_err.iloc[0:1].index[0]
    val=df_err.iloc[0].values[3:]
    print(val)
    correct=[]
    cols=["Base","Très favorable","Plutôt favorable","ST Favorable","Plutôt défavorable","Très défavorable","ST Défavorable","Nsp","Evolution ST Favorable","Evolution ST Défavorable"]
    while len(correct)!=10:
        correct=input()
        correct=[float(x) for x in correct.split(' ')]
    print(correct)
    df.loc[index,cols]=correct

KeyError: 'Très favorable'

In [ ]:
df_err=find_mistake(df)
df_err

In [ ]:

# df.to_pickle('data/'+filename+'.p')